spring:
  application:
    name: spring-cloud-eureka-client
#server:
#  port: 0
eureka:
  healthcheck:
    enabled: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
management:
  endpoint:
    shutdown:
      enabled: true
    heapdump:
      enabled: true
    logfile:
      enabled: true